In simulator.py, I made a function that toggles a nonlocal boolean, and in the while running loop, I put an if boolean condition for the routes to be rendered.
CraftinPark/concurrent-traffic pull request #10
Opened 2024-06-19 07:46 UTC by horlikheng

2024-06-19 07:46 UTC, CraftinPark commented
Task linked: [CU-86b0rn6mq Toggle visibility of routes](https://app.clickup.com/t/86b0rn6mq)

2024-06-19 21:20 UTC, changoug submitted a review, later dismissed
stuff!

2024-06-19 22:27 UTC, changoug requested changes
Good work! render_world may contain other components in the future. Consider passing a flag into render_world instead.

2024-06-19 22:27 UTC, changoug commented on src/simulator/simulator.py
> +            render_world(screen, nodes, edges)
render_world may hold other components in the future. Consider passing a flag through render_world to toggle the routes specifically.

2024-06-26 04:35 UTC, changoug approved these changes

2024-06-26 04:42 UTC, merged