Cu 86b0ud44p car direction reflects route edge it is on
CraftinPark/concurrent-traffic pull request #17
Opened 2024-06-28 00:32 UTC by hyt152004

2024-06-28 00:32 UTC, CraftinPark commented
Task linked: [CU-86b0ud44p car direction reflects route/edge it's on](https://app.clickup.com/t/86b0ud44p)

2024-06-28 20:18 UTC, changoug requested changes

2024-06-28 20:18 UTC, changoug commented on src/classes/route.py
> +def direction_at_route_position(route, position):
Great job man! It looks and works great. Small thing, we're trying to add typing for all functions parameters and returns.

2024-06-28 21:29 UTC, CraftinPark approved these changes

2024-06-29 16:37 UTC, changoug approved these changes
Great stuff my guy

2024-06-29 16:37 UTC, merged