Cu 86b02r1zr collision calculation
CraftinPark/concurrent-traffic pull request #18
Opened 2024-06-29 16:40 UTC by CraftinPark

2024-06-29 16:40 UTC, CraftinPark commented
Task linked: [CU-86b02r1zr 011 collision calculation](https://app.clickup.com/t/86b02r1zr)

2024-06-29 16:42 UTC, CraftinPark commented
uncomment manager.py:68 to see collisions calculation upon car entering manager radius

2024-06-30 03:56 UTC, changoug requested changes
Great job! However, it looks like there may be some issues occurring with the algorithm, as two collisions are showing up. Please confirm and address this

2024-07-05 04:48 UTC, changoug requested changes

2024-07-05 04:48 UTC, changoug commented on src/manager/manager.py
> +def get_collisions(manager: Manager, cur_time: float):
add return type bro

2024-07-05 04:48 UTC, changoug commented on src/manager/manager.py
> +        def world_pos_0(t):
this is ugly bro. make it pretty. bro.

2024-07-05 04:48 UTC, changoug commented on src/manager/manager.py
> +def route_position_at_time(vehicle: Vehicle, time: float):
return type

2024-07-05 04:48 UTC, changoug commented on src/manager/manager.py
> +def time_until_end_of_route(vehicle: Vehicle):
return type

2024-07-05 04:48 UTC, changoug commented on src/manager/manager.py
> +        def distance(t):
Can be a one-liner once you have the functions for it, or separate distance function

2024-07-05 04:48 UTC, changoug commented on src/manager/manager.py
> +        def objective(t):
Same as distance function.

2024-07-05 04:48 UTC, changoug commented on src/manager/manager.py
> +    threshold_distance = 2.5 # will be replaced by Alex's defined safety radius
threshold_distance=2.5 doesn't seem to reflect the current simulation visual. Consider threshold_distance=4, the one we tested.

2024-07-05 04:50 UTC, changoug requested changes

2024-07-05 04:50 UTC, changoug commented on src/manager/manager.py
> +        def world_pos_0(t):
Consider separate function, it is a bit confusing.

2024-07-05 05:24 UTC, changoug approved these changes
Looks gud

2024-07-05 05:24 UTC, merged