Cu 86b0zgw9z zoom ability
CraftinPark/concurrent-traffic pull request #21
Opened 2024-07-03 20:20 UTC by hyt152004

2024-07-03 20:20 UTC, CraftinPark commented
Task linked: [CU-86b0zgw9z Zoom Ability](https://app.clickup.com/t/86b0zgw9z)

2024-07-03 20:41 UTC, CraftinPark requested changes
have you looked into modifying the world_to_screen_vector function? It might be a simpler solution. If we have a world position like (-1,-1) and it maps to screen pos (-200,-200), the magnitude might increase depending on how much has been zoomed and could map to (-300,-300). This could be a good idea, because every object that needs to be zoomed calls "world_to_screen_vector" when rendering. This way we don't have to worry about zoom in the "world position" space. We wouldn't have to pass in a zoom parameter to every render function
But this could be feasible if there is a problem with mentioned approach

2024-07-03 23:34 UTC, hyt152004 commented
> have you looked into modifying the world_to_screen_vector function? It might be a simpler solution. If we have a world position like (-1,-1) and it maps to screen pos (-200,-200), the magnitude might increase depending on how much has been zoomed and could map to (-300,-300). This could be a good idea, because every object that needs to be zoomed calls "world_to_screen_vector" when rendering. This way we don't have to worry about zoom in the "world position" space. We wouldn't have to pass in a zoom parameter to every render function But this could be feasible if there is a problem with mentioned approach

2024-07-05 00:01 UTC, CraftinPark commented
Hi David, great job getting zoom to no longer be a parameter. I think we are almost there.

- [ ] I think we can further remove (and possibly remove entirely) zoom and `get_zoomed_render` from render.py if we make the same modifications for scalars. Within world_to_screen_scalar, we can multiply by zoom_factor. Right now we are doing an if check, and some things like vehicle size have been missed

- [ ] Also, let's have it so that zoom is done multiplicatively, so every time we scroll we multiply the factor by 1.1 or something. This is because adding 1 to the factor is proportionally larger when zoomed out (at 1) than already zoomed in (at 5).

- [ ] let's clean up and have scroll behavior within a function. scroll_handler is a good name off the top of my head.

I've modified your task story points to reflect the amount of work that you're doing, keep up the good work👍

2024-07-08 05:45 UTC, CraftinPark approved these changes
the hard work paid off, looks good

2024-07-08 16:50 UTC, merged