Added names above cars
CraftinPark/concurrent-traffic pull request #24
Opened 2024-07-08 06:08 UTC by horlikheng

Not sure if the texts are too big.

2024-07-08 06:08 UTC, CraftinPark commented
Task linked: [CU-86b0rn727 add names to cars](https://app.clickup.com/t/86b0rn727)

2024-07-08 17:58 UTC, CraftinPark requested changes
Hi Alex, great work. Could we:
- decrease the font size a little
- center the name above the car

2024-07-12 05:21 UTC, changoug approved these changes
looks gud

2024-07-12 05:37 UTC, CraftinPark approved these changes

2024-07-12 05:37 UTC, merged