Cu 86b17nbbc simulation stops when collision
CraftinPark/concurrent-traffic pull request #39
Opened 2024-08-15 02:27 UTC by moraesand

2024-08-15 02:27 UTC, CraftinPark commented
Task linked: [CU-86b17nbbc simulation stops when collision happens](https://app.clickup.com/t/86b17nbbc)

2024-08-15 02:30 UTC, moraesand commented
this task is linked with this task as well: CU-86b1deu5x (cars become red when collided)

2024-08-17 05:28 UTC, changoug requested changes
Some small formatting things, other than that it looks really good. Great stuff man!

2024-08-17 05:28 UTC, changoug commented on src/manager/manager.py
> +def detect_collisions(manager: Manager, vehicles: list[Vehicle], cur_time: float) -> list[Collision]:
Add function description

2024-08-17 05:28 UTC, changoug commented on src/simulator/render.py
> +
Remove extra spacing

2024-08-17 05:28 UTC, changoug commented on src/simulator/render.py
> +from manager.manager import Manager, CAR_COLLISION_DISTANCE, detect_collisions
Remove unused import

2024-08-18 05:16 UTC, changoug approved these changes
Looks gud!

2024-08-18 19:19 UTC, merged