Cu 86b085v5m arc cars
CraftinPark/concurrent-traffic pull request #4
Opened 2024-06-08 15:40 UTC by CraftinPark

2024-06-08 15:40 UTC, CraftinPark commented
Task linked: [CU-86b085v5m 023 'along the arc' vectors, cars able to make turns](https://app.clickup.com/t/86b085v5m)

2024-06-08 19:45 UTC, changoug requested changes

2024-06-08 19:45 UTC, changoug commented on src/manager/manager.py
> +from ..classes.route import route_position_to_world_position
This was giving issues. Changing to:
`from classes.route import...` 
fixed the issue.

2024-06-09 03:38 UTC, changoug approved these changes
looks goated

2024-06-09 03:44 UTC, merged