implemented route id
CraftinPark/concurrent-traffic pull request #9
Opened 2024-06-15 23:04 UTC by hyt152004

2024-06-15 23:04 UTC, CraftinPark commented
Task linked: [CU-86b0rn7m3 implement route id](https://app.clickup.com/t/86b0rn7m3)

2024-06-16 18:20 UTC, changoug requested changes
Good stuff, just some comments on stuff I think that is worth discussing.

2024-06-16 18:20 UTC, changoug commented on src/classes/route.py
> +    id: int                             = None           # vehicle identifier
I think the spacing, while clean, will be harder to keep consistent across all the files we have. Also perhaps id should be generated by the class itself vs being a parameter that is passed in. A global iterator should suffice (every new vehicle increments the id by one), or perhaps some built-in identifier. I will leave that decision up to you.

2024-06-16 18:20 UTC, changoug commented on src/classes/route.py
> +    total_length: float                 = 0              # float representing total length of the route in meters
Same thing with the spacing.

2024-06-16 19:54 UTC, changoug approved these changes
Good stuff!

2024-06-16 20:33 UTC, merged